# Summary
- 자바에는 close()를 통해 닫아줘야 하는 자원들이 많다. 전통적으로는 try-finally를 통해 자원의 닫힘을 보장했다.
- try-finally를 사용하면 try 구문에서 예외가 발생해도 finally 구문은 반드시 실행된다는 이점이 있다. 따라서 자원이 반드시 닫힌다.
- 그런데, finally 구문에서도 예외가 발생하면 어떨까?
  - finally 구문에서 발생한 예외가 try 구문에서 발생한 모든 예외를 덮어버린다.
  - 결과적으로, 디버깅이 굉장히 어렵게 된다. 처음 발생한 에러를 찾을 수가 없게 되기 때문이다

- try-with-resource를 사용하면 처음 발생한 예외가 기록되고 그 다음으로 발생한 에러들 역시 순차적으로 출력된다.
- 결과적으로 try-finally보다 훨씬 디버깅에 유리하다. 예외 없이, try-finally 보다 try-with-resource를 사용하는게 좋다.
---
### try-finally 의 문제점
```cs
public class Sample {

   public void function(){
        System.out.println("기능 1");
        throw new IllegalArgumentException();
    }

    public void close() {
        System.out.println("종료합니다.");
        throw new IllegalStateException();
    }
}
```

- 위와 같은 예제 클래스를 만들었다고 해보자. 첫 번째 기능과 두 번째 기능, close()는 모두 예외를 발생시키는 메서드이다.
- 이 메서드를 아래와 같이 사용한다고 해보자.

```cs
public static void main(String[] args) {
        try (Sample sample = new Sample()) {
            sample.function();
        }
    }
```
- 이 main 메서드를 실행하면 마지막 예외가 위의 두 예외를 덮어버린다. 콘솔에 출력되는 결과를 살펴보면 다음과 같다.
```
기능 1
종료합니다.
Exception in thread "main" java.lang.IllegalStateException
	at Sample.close(Sample.java:15)
	at Main.main(Main.java:14)
```

###  try-with-resource의 사용
- 다행히도 자바 7부터는 try-with-resource를 지원해 위와 같은 문제를 방지할 수 있다.
- try-with-resource를 사용하기 위해선 사용되는 자원이 AutoCloseable 인터페이스를 구현한 상태여야 한다.
  - AutoCloaseable 인터페이스는 close()만을 담고있는 functional 인터페이스다.
  - 위의 Sample 예시를 해당 인터페이스를 구현한 인터페이스로 바꾸면 아래와 같다.
```cs
public class Sample implements AutoCloseable{

    public void function(){
        System.out.println("기능 1");
        throw new IllegalArgumentException();
    }

    @Override
    public void close() {
        System.out.println("종료합니다.");
        throw new IllegalStateException();
    }
}
```
